"""add github_repo_id and is_owner to repos

Revision ID: 33320354835e
Revises: ef929fc58c73
Create Date: 2026-08-06 13:05:49.811018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33320354835e'
down_revision: Union[str, Sequence[str], None] = 'ef929fc58c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('github_repo_id', sa.Integer(), nullable=False))
    op.add_column('repos', sa.Column('is_owner', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_repos_github_repo_id'), 'repos', ['github_repo_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repos_github_repo_id'), table_name='repos')
    op.drop_column('repos', 'is_owner')
    op.drop_column('repos', 'github_repo_id')
    # ### end Alembic commands ###
