"""add owner_login to repos

Revision ID: afbba6070634
Revises: 33320354835e
Create Date: 2026-08-06 21:28:43.062126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afbba6070634'
down_revision: Union[str, Sequence[str], None] = '33320354835e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('owner_login', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repos', 'owner_login')
    # ### end Alembic commands ###
