"""add github_access_token_encrypted to users

Revision ID: ef929fc58c73
Revises: 6a07c4c3a82a
Create Date: 2026-08-06 12:24:51.992056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef929fc58c73'
down_revision: Union[str, Sequence[str], None] = '6a07c4c3a82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_access_token_encrypted', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_access_token_encrypted')
    # ### end Alembic commands ###
